#!/usr/bin/env bash

apt-list-sources () {
	apt-cache policy "$1" | sed -rn '/^ \*\*\* /{:loop;n;s/^     [- 0-9]{6} //p;tloop}'
}

apt-list-installed () {
	dpkg-query --list | tail -n +6 | sed -rn 's/^.i..([^ ]*) *.*$/\1/p'
}

tempdir="$(mktemp -d --tmpdir apt-list-unexpected-sources."$$".XXXXX)"
trap 'rm -r -- "$tempdir"' EXIT

for pkg in $(apt-list-installed); do
	first_source=
	while read -r line; do
		if [[ -z "$first_source" ]]; then
			first_source="$line"
		fi
	done < <(apt-list-sources "$pkg")

	echo "$pkg" >>"$tempdir"/"${first_source//\//_}"
done

for sourcefile in "$tempdir"/*; do
	basename="$(basename "$sourcefile")"
	echo "${basename//_/\/}":
	sed 's/^/    /' "$sourcefile"
done

# vim: ft=bash noet ts=8
